apiVersion: v1
kind: Service
metadata:
  name: python-hello
  namespace: python-namespace
spec:
  type: NodePort
  selector:
    app: python-hello
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30991 # updated 30992 to 30991 for --sync-garbage-collection=true enabled in flux
