kind: Service
metadata:
  name: python-hello
  namespace: python-namspace
spec:
  type: NodePort
  selector:
    app: python-hello
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30992
